export default {
    getRandomWordIndexes,
    getWords,
    getWordIndexesFromURL
}


function getWordIndexesFromURL(): number[] {
    const arg = window.location.search.substr(1)
    const values: number[] = arg
        .split(",")
        .map(txt => parseInt(`0x${txt}`, 16))
    let isValid = true
    for (const v of values) {
        if (isNaN(v)) {
            isValid = false
            break
        }
    }
    return isValid && values.length === 25 ? shuffle(values) : []
}

function getRandomWordIndexes(): number[] {
    if (window.location.search.length > 1) {
        // Get words from URL.
        const values = getWordIndexesFromURL()
        console.info("values=", values)
        console.info("window.location=", window.location)
        if (values.length === 25) return values
    }

    // Random words.
    const indexes: number[] = []
    for (let i = 0; i < WORDS.length; i++) indexes.push(i)
    return shuffle(indexes).slice(0, 25)
}

function getWords(indexes: number[]): string[] {
    return indexes.map(idx => WORDS[idx])
}

function shuffle(arr: any[]): any[] {
    const len = arr.length
    for (let i = 0; i < len; i++) {
        const k = Math.floor(Math.random() * len)
        const tmp = arr[i]
        arr[i] = arr[k]
        arr[k] = tmp
    }
    return arr
}

const WORDS = [
    "Absence",
    "Abus",
    "Acajou ",
    "Accident",
    "Accordéon",
    "Accès",
    "Acteur",
    "Adulte",
    "Agneau",
    "Agriculteur ",
    "Ailleurs",
    "Alarme",
    "Amour",
    "Amérique",
    "Ananas",
    "Animal",
    "Apocalypse",
    "Appel",
    "Apprentissage",
    "Appréhension",
    "Aquarium",
    "Araignée",
    "Araignée",
    "Arbalète",
    "Arbre",
    "Arcade",
    "Archipel",
    "Architecte",
    "Archéologue",
    "Argent",
    "Arobase",
    "Arrivée",
    "Arrêt",
    "Article",
    "Ascenseur",
    "Ascension",
    "Aspirateur",
    "Athlète",
    "Attente",
    "Attitude",
    "Attraction",
    "Autoroute",
    "Avalanche ",
    "Avance",
    "Avant",
    "Aventurier",
    "Avion ",
    "Avion",
    "Aviron",
    "Avocat",
    "Avocat",
    "Avril",
    "Axe",
    "Babine",
    "Baccalauréat",
    "Baguette",
    "Baguette",
    "Balade",
    "Balai",
    "Ballon ",
    "Banjo",
    "Banque",
    "Banquise",
    "Barbe",
    "Barman",
    "Bassine",
    "Bateau ",
    "Batterie",
    "Beau",
    "Beauté",
    "Berger",
    "Bilboquet",
    "Billard",
    "Blanc",
    "Bonheur",
    "Bonne",
    "Bonzaï",
    "Bord",
    "Bouche",
    "Boucher",
    "Bouchon",
    "Boucle",
    "Bougie",
    "Bouillotte",
    "Boulanger",
    "Boule",
    "Bourricot",
    "Bouteille",
    "Bouée",
    "Boxe",
    "Braguette",
    "Bretzel",
    "Brocante",
    "Bronze",
    "Brosse à dent ",
    "Brouhaha",
    "Brouillard",
    "Bruit",
    "Brun",
    "Brésil",
    "Buche",
    "Bureau",
    "But",
    "Bébé",
    "Bête",
    "Bûcheron ",
    "Cabane",
    "Cache",
    "Caillou",
    "Caissière",
    "Calendrier",
    "Camion",
    "Canapé",
    "Canon",
    "Capot",
    "Capucine",
    "Car",
    "Carotte",
    "Carreau",
    "Carte",
    "Carte",
    "Caïman ",
    "Ceinture",
    "Cent",
    "Cercle",
    "Cerf",
    "Chaise",
    "Chaleur",
    "Champignon",
    "Chance",
    "Chance",
    "Chance",
    "Chanteur d'opéra",
    "Chanteur",
    "Chapeau",
    "Chariot",
    "Chat",
    "Chaussette",
    "Chaussette",
    "Cheminée",
    "Cheveux",
    "Chien",
    "Chien",
    "Chine",
    "Chirurgien",
    "Chlorophylle ",
    "Chocolat",
    "Choix",
    "Chèque",
    "Cirage",
    "Cire",
    "Cirque",
    "Ciseau",
    "Citrouille",
    "Classeur",
    "Clavier",
    "Clitoris",
    "Cloche",
    "Cloporte",
    "Clown ",
    "Club",
    "Coccyx ",
    "Coco",
    "Coffre-fort",
    "Coiffeur",
    "Comité",
    "Communion",
    "Communiste",
    "Compartiment",
    "Complexe",
    "Complication",
    "Comptable",
    "Compte",
    "Concombre",
    "Conquistador",
    "Conspirateur",
    "Controverse",
    "Copine",
    "Coq",
    "Coquelicot ",
    "Corbeau",
    "Corde",
    "Cornemuse",
    "Cornichon",
    "Correspondance",
    "Cortège",
    "Coureur",
    "Courgette",
    "Course",
    "Cousin",
    "Couteau ",
    "Couture",
    "Couverture",
    "Crapaud",
    "Cravate",
    "Crayon",
    "Crayon",
    "Creux",
    "Croix",
    "Crotte",
    "Crâne",
    "Cuisinier",
    "Cure-dents",
    "Cycle",
    "Cœur",
    "Dame",
    "Danger",
    "Danseuse ",
    "Danseuse de ballet",
    "Dent",
    "Dentier",
    "Dentiste",
    "Descente",
    "Designer ",
    "Dessert",
    "Diapason",
    "Direction",
    "Disparition",
    "Disque",
    "Distributeur",
    "Docteur",
    "Dodo",
    "Dompteur",
    "Drap",
    "Drap",
    "Drapeau ",
    "Dune",
    "Dé",
    "Débutant ",
    "Délais",
    "Départ",
    "Département",
    "Désert",
    "Détective  ",
    "Ellipse",
    "Emballage",
    "Enceinte",
    "Encouragement",
    "Enfant",
    "Ensemble",
    "Entourage",
    "Essai",
    "Exemple",
    "Explosion",
    "Face",
    "Fait",
    "Famille",
    "Fauteuil",
    "Faux",
    "Femme",
    "Ferraille",
    "Feu",
    "Feutre",
    "Figure",
    "Fil",
    "Fils",
    "Fin",
    "Fleuriste ",
    "Flibustier",
    "Flipper",
    "Flou",
    "Fois",
    "Force",
    "Forme",
    "Formule",
    "Forteresse",
    "Forêt",
    "Foule",
    "Fourchette",
    "Fourmis",
    "Frigo",
    "Fromage",
    "Frère",
    "Fête",
    "Galaxie",
    "Gangster",
    "Garage",
    "Garagiste",
    "Garde forestier",
    "Gare",
    "Gaz",
    "Gazelle",
    "Genou",
    "Gifle",
    "Girafe",
    "Gland",
    "Glaçon",
    "Gondolier",
    "Gospel",
    "Gothique",
    "Goulot",
    "Gramme",
    "Graphique",
    "Grelot",
    "Grenouille ",
    "Gros",
    "Grue",
    "Grèce",
    "Guenon",
    "Guirlande",
    "Géologue",
    "Harpon",
    "Hautbois",
    "Herbe",
    "Hiérarchie",
    "Hochet",
    "Horloge",
    "Horoscope ",
    "Humour",
    "Hypocrisie",
    "Hérisson ",
    "Iceberg",
    "Identité",
    "Igloo",
    "Impression",
    "Inconnu",
    "Indien",
    "Infirmier",
    "Informaticien",
    "Information",
    "Installation",
    "Interrogation",
    "Intersection",
    "Jambe",
    "Jardin",
    "Jargon",
    "Javelot",
    "Jazz",
    "Jeton",
    "Jeu de cartes",
    "Jeu",
    "Joue",
    "Journal",
    "Journal",
    "Journaliste ",
    "Journée",
    "Jupiter",
    "Kaléidoscope ",
    "Kangourou",
    "Kiwi",
    "Klaxon ",
    "Koala",
    "Labyrinthe",
    "Lac",
    "Lampe",
    "Lampe",
    "Libraire",
    "Lieu",
    "Limite ",
    "Lion",
    "Lionne",
    "Liste",
    "Lit",
    "Livre",
    "Livreur  ",
    "Logiciel",
    "Logique",
    "Logo",
    "Losange",
    "Lourd",
    "Lumière",
    "Lune",
    "Lunettes",
    "Lynx",
    "Lâcheté",
    "Lèvre",
    "Machette",
    "Magicien",
    "Mail",
    "Majeur ",
    "Malheur",
    "Maman",
    "Manivelle",
    "Marche",
    "Marionnettiste",
    "Marque",
    "Marre",
    "Mars",
    "Martyre",
    "Mascarade",
    "Massacre",
    "Matelas",
    "Maître-nageur ",
    "Membre",
    "Mensonge",
    "Menthe",
    "Mer ",
    "Message",
    "Minable",
    "Mine",
    "Mineur",
    "Moi",
    "Molette",
    "Monde",
    "Moniteur de ski",
    "Montagne",
    "Montgolfière",
    "Montée",
    "Moquette",
    "Mort",
    "Mot",
    "Moule",
    "Moult",
    "Mousse",
    "Mouton",
    "Musique",
    "Mère",
    "Médecin",
    "Médecine",
    "Métallurgie ",
    "Métamorphose",
    "Métaphore",
    "Métro",
    "Mûre",
    "Nageur ",
    "Nain",
    "Narrateur",
    "Neige",
    "Note",
    "Nouille",
    "Nourriture",
    "Nuage",
    "Néant",
    "Nœud",
    "Objectif",
    "Occupation",
    "Océan",
    "Océanologue",
    "Oiseau ",
    "Ordinateur",
    "Organisation",
    "Orthophoniste",
    "Ortie",
    "Ours-en-peluche",
    "Ouïe",
    "Oxygène",
    "Panique",
    "Papier",
    "Papillon",
    "Paranoïa",
    "Parcours",
    "Pardon",
    "Parenthèse",
    "Parole",
    "Parti",
    "Partition",
    "Pauvre",
    "Peau",
    "Peinture",
    "Pelle",
    "Peluche",
    "Pensée",
    "Personne",
    "Perte",
    "Peuple",
    "Peur",
    "Pharmacien ",
    "Phoque",
    "Photographe",
    "Piano",
    "Pick Pocket",
    "Pilote ",
    "Pion",
    "Planète",
    "Pleurs",
    "Plombier",
    "Plongeon",
    "Podium",
    "Poil",
    "Point",
    "Pointe",
    "Poire",
    "Poison",
    "Poisson",
    "Policier",
    "Politique",
    "Pomme",
    "Pompier",
    "Portail",
    "Porte",
    "Porte-manteau",
    "Porte-monnaie",
    "Position",
    "Poste",
    "Pot",
    "Poterie",
    "Poubelle",
    "Poulpe",
    "Poumon",
    "Poussière",
    "Poutre",
    "Pouvoir",
    "Pouvoir",
    "Principe",
    "Printemps",
    "Prise",
    "Problème",
    "Procès",
    "Professeur ",
    "Professeur",
    "Prudemment ",
    "Prune",
    "Présence",
    "Préservatif",
    "Président ",
    "Président",
    "Psychiatre",
    "Pureté",
    "Puzzle",
    "Pyramide",
    "Pédiatr",
    "Péripétie",
    "Pétrole ",
    "Pêche",
    "Pêcheur",
    "Quadriceps",
    "Quadrilatère",
    "Qualification  ",
    "Quartz",
    "Question ",
    "Quotidien",
    "Radar",
    "Radiateur",
    "Radio",
    "Radis",
    "Rapide",
    "Rapport",
    "Raquette",
    "Rassemblement",
    "Rat",
    "Rayon",
    "Rectangle",
    "Renégat",
    "Repas",
    "Reporter",
    "Reproche",
    "Responsable",
    "Ressenti",
    "Retrait",
    "Rhododendron",
    "Rhum",
    "Riche",
    "Rien",
    "Robot",
    "Rocher",
    "Rongeur",
    "Rose",
    "Rotation",
    "Rouge",
    "Route",
    "Rugby",
    "Réalisateur",
    "Régulation",
    "Réparateur Automobile",
    "Révolution",
    "Rêve",
    "Sac",
    "Salade",
    "Salle",
    "Sang",
    "Sans-abri",
    "Savane",
    "Savoir",
    "Scarabée",
    "Scientifique",
    "Scooter",
    "Scorpion",
    "Seau",
    "Sein",
    "Senteur",
    "Serrurier ",
    "Serveur",
    "Seuil",
    "Sexe",
    "Sifflet",
    "Silence",
    "Siège",
    "Slip",
    "Sol",
    "Soleil",
    "Sorcellerie",
    "Sorcière",
    "Souffle",
    "Soupir",
    "Souris",
    "Soutien",
    "Spirale",
    "Strophe",
    "Styliste",
    "Stylo",
    "Sucette",
    "Surligneur",
    "Symptôme",
    "Séisme",
    "Sœur ",
    "Table",
    "Tablette",
    "Tabouret",
    "Tam-tam",
    "Tambourin",
    "Tapis",
    "Tartiflette",
    "Taupe",
    "Temps",
    "Tenue",
    "Terrain",
    "Terre",
    "Test",
    "Texte",
    "Thym",
    "Tige",
    "Tigre",
    "Toile",
    "Toiletteur",
    "Tokyo",
    "Tomate",
    "Tonneau",
    "Touche",
    "Tourisme",
    "Tout",
    "Tracteur",
    "Traducteur",
    "Traitement",
    "Triangle",
    "Tristesse",
    "Trombone",
    "Trou",
    "Trou",
    "Trousse ",
    "Truc",
    "Trêve",
    "Tuile",
    "Tunique",
    "Tyran",
    "Tétine",
    "Tête",
    "Ukulélé",
    "Usuel",
    "Vagin",
    "Vague",
    "Valeur",
    "Valise",
    "Valse",
    "Vase",
    "Vautour",
    "Vendredi",
    "Ventilateur",
    "Verre",
    "Vert",
    "Vestiaire",
    "Victoire",
    "Vie",
    "Ville",
    "Vin",
    "Violence",
    "Virage",
    "Voiture",
    "Voyage",
    "Vécu",
    "Vérité",
    "Vétérinaire",
    "Whisky ",
    "Xylophone",
    "Zygomatique ",
    "Zèbre",
    "Âne",
    "Âtre ",
    "Éboueur",
    "Ébène",
    "Ébéniste",
    "École",
    "Égypte",
    "Élastique",
    "Éleveur ",
    "Éléphant",
    "Émeraude",
    "Épluchage ",
    "Épée",
    "Étape",
    "Éviction",
    "Île"
]
